### ISSUE TITLE
No response after run  "python cross_prediction.py -r ../datasets/ -s 600"

### ISSUE THREAD

**Issue by don-lin** [Ruixinhua/AncientDiscovery#2]
After I run "python cross_prediction.py -r ../datasets/ -s 600", nothing happened.
![image](https://user-images.githubusercontent.com/23432402/94984516-647f9380-057f-11eb-959d-69c4791a1c86.png)
![image](https://user-images.githubusercontent.com/23432402/94984524-77926380-057f-11eb-9555-60f366611b94.png)

**Comment by Ruixinhua** [comment]
Because you did not download the dataset
